# Generated by Django 3.2.8 on 2021-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('ADM', 'Admiral'), ('CPT', 'Captain'), ('CMNDR', 'Commander'), ('LTC', 'Lt. Commander'), ('LT', 'Lieutenant'), ('ESN', 'Ensign')], default='ESN', max_length=15),
        ),
    ]
