# Generated by Django 3.2.8 on 2022-01-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('CPT', 'Captain'), ('XO', 'First Officer'), ('ENG', 'Chief Engineer'), ('SCI', 'Science Officer'), ('PIL', 'Pilot'), ('DOC', 'Doctor')], max_length=15, null=True),
        ),
    ]
